import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function formatIQD(amount: number): string {
  return new Intl.NumberFormat('ar-IQ', {
    style: 'decimal',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount) + ' د.ع';
}

/**
 * Generate order number (FALLBACK ONLY - should be generated by backend)
 * This is only used as a last resort if the backend fails to provide orderNumber
 * Uses timestamp-based unique identifier instead of random numbers
 */
export function generateOrderNumber(): string {
  const date = new Date();
  const year = date.getFullYear().toString().slice(-2);
  const month = (date.getMonth() + 1).toString().padStart(2, '0');
  const day = date.getDate().toString().padStart(2, '0');

  // Use timestamp milliseconds for uniqueness (last 4 digits)
  // This ensures orders created at different times have different numbers
  const timestamp = Date.now();
  const sequence = (timestamp % 10000).toString().padStart(4, '0');

  // صيغة رقم الطلب: FW-YYMMDD-XXXX
  return `FW-${year}${month}${day}-${sequence}`;
}

export function formatDate(date: Date): string {
  return new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Asia/Baghdad',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
}

export function formatShortDate(date: Date): string {
  return new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Asia/Baghdad',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(date);
}

