import { db } from "../server/storage";
import { products } from "../shared/schema";

// Professional, SEO-optimized product database for FreshWater aquarium e-commerce
// Following 2025 e-commerce best practices with unique descriptions, detailed specifications,
// and comprehensive product information

const seedProducts = [
  // ==================== TROPICAL FISH ====================
  {
    id: "betta-male-mixed",
    slug: "betta-splendens-male-fighter-fish",
    name: "Betta Splendens - سمكة بيتا الذكر المقاتلة",
    brand: "FreshWater Premium",
    category: "Fish",
    subcategory: "Tropical Fish",
    description: "اكتشف جمال سمكة البيتا المقاتلة (Betta splendens) - واحدة من أجمل أسماك الزينة في العالم. تتميز بألوانها الزاهية وزعانفها الطويلة المتدفقة التي تشبه الحرير. البيتا سمكة ذكية وشخصية فريدة، مثالية للمبتدئين والخبراء على حد سواء. تعيش بسعادة في أحواض صغيرة (5 جالون على الأقل) وتتكيف مع مجموعة واسعة من ظروف المياه. كل سمكة بيتا لها شخصيتها الفريدة وستصبح رفيقاً ممتعاً في حوضك. | Discover the stunning Siamese Fighting Fish (Betta splendens) - one of the world's most beautiful aquarium fish. Features vibrant colors and flowing, silk-like fins. Intelligent with unique personality, perfect for beginners and experts. Thrives in small tanks (minimum 5 gallons) and adapts to a wide range of water conditions. Each betta has its own unique character and will become an entertaining companion in your aquarium.",
    price: "12000",
    currency: "IQD",
    images: ["/products/betta-fish.jpg"],
    thumbnail: "/products/betta-fish.jpg",
    rating: "4.8",
    reviewCount: 142,
    stock: 45,
    lowStockThreshold: 10,
    isNew: false,
    isBestSeller: true,
    specifications: {
      scientificName: "Betta splendens",
      maxSize: "7 cm",
      minTankSize: "20 liters (5 gallons)",
      temperature: "24-28°C (75-82°F)",
      pH: "6.8-7.5",
      difficulty: "easy",
      temperament: "Aggressive with other males",
      diet: "Carnivore - pellets, frozen/live foods",
      lifespan: "3-5 years",
      waterType: "Freshwater",
      origin: "Thailand, Cambodia, Vietnam",
      compatibility: "Keep males separate, females can school",
      ecoFriendly: true
    }
  },
  {
    id: "guppy-mixed-colors",
    slug: "guppy-poecilia-reticulata-mixed",
    name: "Guppy Mixed Colors - أسماك الجوبي الملونة",
    brand: "FreshWater Premium",
    category: "Fish",
    subcategory: "Tropical Fish",
    description: "أسماك الجوبي (Poecilia reticulata) - الخيار الأمثل للمبتدئين! تشتهر بألوانها المتنوعة وسهولة تربيتها وطبيعتها السلمية. الجوبي سمكة نشطة وحيوية تضيف حركة مستمرة وجمالاً لحوضك. تتكاثر بسهولة وتنتج صغاراً جميلة، مما يجعلها مثالية للهواة الذين يرغبون في تجربة تربية الأسماك. تعيش في مجموعات وتتعايش مع معظم الأسماك المجتمعية الأخرى. | Guppy fish (Poecilia reticulata) - the ultimate beginner's choice! Known for vibrant colors, easy care, and peaceful nature. Active and lively, adding constant movement and beauty to your tank. Breeds easily producing beautiful fry, perfect for hobbyists wanting to experience fish breeding. Lives in groups and compatible with most community fish.",
    price: "3000",
    currency: "IQD",
    images: ["/products/guppy-mixed.jpg"],
    thumbnail: "/products/guppy-mixed.jpg",
    rating: "4.9",
    reviewCount: 287,
    stock: 120,
    lowStockThreshold: 30,
    isNew: false,
    isBestSeller: true,
    specifications: {
      scientificName: "Poecilia reticulata",
      maxSize: "5 cm",
      minTankSize: "40 liters (10 gallons)",
      temperature: "22-28°C (72-82°F)",
      pH: "7.0-8.5",
      difficulty: "easy",
      temperament: "Peaceful",
      diet: "Omnivore - flakes, pellets, vegetables",
      lifespan: "2-3 years",
      waterType: "Freshwater",
      origin: "South America",
      compatibility: "Excellent community fish",
      ecoFriendly: true,
      breeding: "Very easy - livebearers"
    }
  },
  {
    id: "goldfish-common",
    slug: "goldfish-carassius-auratus",
    name: "Goldfish Common - السمكة الذهبية",
    brand: "FreshWater Premium",
    category: "Fish",
    subcategory: "Coldwater Fish",
    description: "السمكة الذهبية (Carassius auratus) - الأكثر شهرة في العالم! سمكة قوية وطويلة العمر يمكن أن تعيش لعقود مع الرعاية المناسبة. مثالية للأحواض الخارجية والداخلية الكبيرة. تتميز بذكائها وقدرتها على التعرف على مالكها والتفاعل معه. تحتاج إلى مساحة واسعة وترشيح قوي بسبب إنتاجها العالي للفضلات. متوفرة بألوان متنوعة وأشكال جميلة. استثمار طويل الأمد سيجلب الفرح لسنوات عديدة. | The Goldfish (Carassius auratus) - world's most famous fish! Hardy and long-lived, can survive for decades with proper care. Perfect for large indoor and outdoor ponds. Intelligent, recognizes owners and interacts. Requires ample space and strong filtration due to high waste production. Available in various colors and beautiful forms. A long-term investment bringing joy for many years.",
    price: "8000",
    currency: "IQD",
    images: ["/products/goldfish.jpg"],
    thumbnail: "/products/goldfish.jpg",
    rating: "4.7",
    reviewCount: 198,
    stock: 65,
    lowStockThreshold: 15,
    isNew: false,
    isBestSeller: true,
    specifications: {
      scientificName: "Carassius auratus",
      maxSize: "30 cm (can grow larger in ponds)",
      minTankSize: "150 liters (40 gallons) for 1-2 fish",
      temperature: "18-24°C (64-75°F)",
      pH: "7.0-8.0",
      difficulty: "easy",
      temperament: "Peaceful",
      diet: "Omnivore - pellets, vegetables, live food",
      lifespan: "10-30 years",
      waterType: "Freshwater - coldwater",
      origin: "China",
      compatibility: "Good with other goldfish",
      ecoFriendly: true
    }
  },
  {
    id: "neon-tetra",
    slug: "neon-tetra-paracheirodon-innesi",
    name: "Neon Tetra - نيون تترا",
    brand: "FreshWater Premium",
    category: "Fish",
    subcategory: "Tropical Fish",
    description: "نيون تترا (Paracheirodon innesi) - جوهرة الأمازون المضيئة! واحدة من أجمل أسماك الأحواض المجتمعية بخطها الأزرق النيوني المتألق والبطن الأحمر الزاهي. تعيش في مجموعات كبيرة (15+ سمكة) وتخلق عرضاً بصرياً خلاباً. سلمية تماماً ومثالية للأحواض المزروعة. صغيرة الحجم لكن كبيرة التأثير - ستضيء حوضك حرفياً! تتطلب مياه نظيفة ومستقرة وإضاءة متوسطة لإظهار ألوانها الكاملة. | Neon Tetra (Paracheirodon innesi) - Amazon's glowing gem! One of the most beautiful community fish with brilliant neon blue stripe and vibrant red belly. Lives in large schools (15+ fish) creating stunning visual display. Completely peaceful and perfect for planted tanks. Small in size but huge in impact - will literally light up your aquarium! Requires clean, stable water and moderate lighting to show full colors.",
    price: "2500",
    currency: "IQD",
    images: ["/products/neon-tetra.jpg"],
    thumbnail: "/products/neon-tetra.jpg",
    rating: "4.8",
    reviewCount: 256,
    stock: 200,
    lowStockThreshold: 50,
    isNew: false,
    isBestSeller: true,
    specifications: {
      scientificName: "Paracheirodon innesi",
      maxSize: "4 cm",
      minTankSize: "40 liters (10 gallons)",
      temperature: "20-26°C (68-79°F)",
      pH: "6.0-7.0",
      difficulty: "easy",
      temperament: "Peaceful - schooling fish",
      diet: "Omnivore - micro pellets, flakes",
      lifespan: "5-10 years",
      waterType: "Freshwater - soft, acidic preferred",
      origin: "South America - Amazon Basin",
      compatibility: "Excellent community fish",
      ecoFriendly: true,
      minimumGroup: "15+ fish"
    }
  },
  {
    id: "cherry-shrimp",
    slug: "cherry-shrimp-neocaridina-davidi",
    name: "Cherry Shrimp Red - جمبري الكرز الأحمر",
    brand: "FreshWater Premium",
    category: "Fish",
    subcategory: "Invertebrates",
    description: "جمبري الكرز الأحمر (Neocaridina davidi) - منظف الحوض الطبيعي! لونه الأحمر الزاهي يضيف بعداً جمالياً مذهلاً للأحواض المزروعة. يتغذى على الطحالب وبقايا الطعام، مما يساعد في الحفاظ على نظافة الحوض. سهل التربية والتكاثر، حتى المبتدئين يمكنهم نجاح تكاثره. سلمي تماماً ويتعايش مع معظم الأسماك الصغيرة. إضافة ممتازة للأحواض البيئية ومثالي للأحواض النانو. شاهدها تتسلق النباتات وتنظف الأسطح - ترفيه وفائدة! | Red Cherry Shrimp (Neocaridina davidi) - nature's aquarium cleaner! Vibrant red color adds stunning aesthetic to planted tanks. Feeds on algae and food debris, helping maintain tank cleanliness. Easy to breed and reproduce, even beginners can successfully breed them. Completely peaceful and compatible with most small fish. Excellent addition to eco-systems and perfect for nano tanks. Watch them climb plants and clean surfaces - entertainment and benefit!",
    price: "4000",
    currency: "IQD",
    images: ["/products/cherry-shrimp.jpg"],
    thumbnail: "/products/cherry-shrimp.jpg",
    rating: "4.9",
    reviewCount: 178,
    stock: 85,
    lowStockThreshold: 20,
    isNew: false,
    isBestSeller: true,
    specifications: {
      scientificName: "Neocaridina davidi",
      maxSize: "3-4 cm",
      minTankSize: "20 liters (5 gallons)",
      temperature: "18-28°C (64-82°F)",
      pH: "6.5-8.0",
      difficulty: "easy",
      temperament: "Peaceful",
      diet: "Omnivore - algae, biofilm, shrimp pellets",
      lifespan: "1-2 years",
      waterType: "Freshwater",
      origin: "Taiwan (captive bred)",
      compatibility: "Avoid large/aggressive fish",
      ecoFriendly: true,
      breeding: "Very easy in aquarium"
    }
  },

  // ==================== AQUARIUM PLANTS ====================
  {
    id: "anubias-nana",
    slug: "anubias-nana-live-aquarium-plant",
    name: "Anubias Nana - نبات أنوبياس نانا الطبيعي",
    brand: "Aquatic Plants Premium",
    category: "Plants",
    subcategory: "Live Plants",
    description: "أنوبياس نانا - النبات المثالي للمبتدئين! نبات أفريقي قوي ومتحمل يزدهر في ظروف الإضاءة المنخفضة. لا يتطلب CO2 أو تسميد مكثف، مما يجعله مثالياً للأحواض منخفضة الصيانة. أوراقه الخضراء الداكنة السميكة تضيف ملمساً طبيعياً جميلاً. يمكن ربطه بالأحجار أو الأخشاب لإنشاء تصاميم طبيعية مذهلة. ينمو ببطء، لذا يحتفظ بشكله لفترة طويلة. مقاوم للطحالب وآمن لمعظم الأسماك. استثمار واحد يدوم سنوات! | Anubias Nana - the perfect beginner plant! Hardy African plant thriving in low-light conditions. Requires no CO2 or intensive fertilization, ideal for low-maintenance tanks. Thick dark green leaves add beautiful natural texture. Can be attached to rocks or driftwood creating stunning natural designs. Slow-growing, maintains shape for extended periods. Algae-resistant and safe for most fish. One investment lasting years!",
    price: "18000",
    currency: "IQD",
    images: ["/products/anubias-nana.jpg"],
    thumbnail: "/products/anubias-nana.jpg",
    rating: "4.9",
    reviewCount: 234,
    stock: 95,
    lowStockThreshold: 20,
    isNew: false,
    isBestSeller: true,
    specifications: {
      scientificName: "Anubias barteri var. nana",
      maxHeight: "10-15 cm",
      lighting: "Low to Medium",
      difficulty: "easy",
      growthRate: "Slow",
      placement: "Foreground to Midground",
      CO2: "Not required (beneficial)",
      temperature: "22-28°C (72-82°F)",
      pH: "6.0-8.0",
      propagation: "Rhizome division",
      ecoFriendly: true,
      origin: "West Africa - Cameroon",
      specialFeature: "Can grow on hardscape - don't bury rhizome"
    }
  },
  {
    id: "java-moss",
    slug: "java-moss-taxiphyllum-barbieri",
    name: "Java Moss - طحلب جافا الطبيعي",
    brand: "Aquatic Plants Premium",
    category: "Plants",
    subcategory: "Mosses",
    description: "طحلب جافا (Taxiphyllum barbieri) - أقوى نبات مائي على الإطلاق! ينمو في أي ظروف تقريباً - من الإضاءة المنخفضة جداً إلى العالية. مثالي لتغطية الأخشاب والأحجار والشبكات لخلق مناظر طبيعية خلابة. يوفر مخبأ مثالي لصغار الأسماك والجمبري. ينقي المياه بشكل طبيعي ويمتص النيترات. سهل الانتشار - قطعة واحدة تتحول إلى حديقة كاملة! يحبه مربو الجمبري والأسماك على حد سواء. لا يحتاج تربة أو زراعة، فقط ثبته وشاهده ينمو! | Java Moss (Taxiphyllum barbieri) - the toughest aquatic plant ever! Grows in almost any conditions - from very low to high lighting. Perfect for covering driftwood, rocks, and mesh creating stunning natural landscapes. Provides ideal hiding place for fish fry and shrimp. Naturally purifies water and absorbs nitrates. Easy propagation - one piece transforms into entire garden! Loved by shrimp and fish breeders alike. Needs no substrate or planting, just attach and watch it grow!",
    price: "12000",
    currency: "IQD",
    images: ["/products/java-moss.jpg"],
    thumbnail: "/products/java-moss.jpg",
    rating: "4.8",
    reviewCount: 189,
    stock: 110,
    lowStockThreshold: 25,
    isNew: false,
    isBestSeller: true,
    specifications: {
      scientificName: "Taxiphyllum barbieri",
      maxHeight: "Forms carpet/wall",
      lighting: "Low to High - adaptable",
      difficulty: "easy",
      growthRate: "Medium to Fast",
      placement: "Any - very versatile",
      CO2: "Not required",
      temperature: "15-30°C (59-86°F)",
      pH: "5.0-9.0 - very adaptable",
      propagation: "Division - cut and replant",
      ecoFriendly: true,
      origin: "Southeast Asia",
      specialFeature: "Perfect for breeding tanks and aquascaping"
    }
  },

  // ==================== AQUARIUM TANKS ====================
  {
    id: "trigger-ss-600-60cm",
    slug: "trigger-systems-ss-600-60cm-aquarium",
    name: "Trigger Systems SS-600 Aquarium 60cm - حوض تريجر 60 سم",
    brand: "Trigger",
    category: "Aquariums",
    subcategory: "Glass Tanks",
    description: "حوض Trigger SS-600 المتميز - الحل الكامل لهواة الأحواض الجادين! صُنع من زجاج فائق الشفافية بسمك مثالي لضمان المتانة والأمان. التصميم العصري بحواف نظيفة وسيليكون عالي الجودة. الحجم المثالي (60 سم) يناسب معظم المساحات ويوفر بيئة ممتازة لمجموعة واسعة من الأسماك. سهل الصيانة والتنظيف. يأتي بضمان الشركة المصنعة. استثمر في جودة تدوم - حوض يرافقك لسنوات! | Trigger SS-600 Premium Aquarium - complete solution for serious hobbyists! Made from ultra-clear glass with optimal thickness ensuring durability and safety. Modern design with clean edges and high-quality silicone. Ideal size (60cm) fits most spaces providing excellent environment for wide range of fish. Easy maintenance and cleaning. Comes with manufacturer warranty. Invest in lasting quality - an aquarium companion for years!",
    price: "175000",
    currency: "IQD",
    images: ["/products/trigger-ss-600.jpg"],
    thumbnail: "/products/trigger-ss-600.jpg",
    rating: "4.7",
    reviewCount: 87,
    stock: 15,
    lowStockThreshold: 5,
    isNew: false,
    isBestSeller: true,
    specifications: {
      dimensions: "60 x 30 x 35 cm (L x W x H)",
      volume: "63 liters",
      glassThickness: "6mm",
      weight: "12 kg (empty)",
      material: "Ultra-clear glass",
      sealant: "High-grade aquarium silicone",
      difficulty: "easy",
      suitableFor: "Tropical, Coldwater, Planted tanks",
      maxFishLoad: "25-30 small fish",
      warranty: "1 year manufacturer warranty",
      ecoFriendly: true
    }
  },
  {
    id: "boshuo-ys-500-50cm",
    slug: "boshuo-ys-500-50cm-aquarium-tank",
    name: "Boshuo YS-500 Aquarium 50cm - حوض بوشو 50 سم",
    brand: "Boshuo",
    category: "Aquariums",
    subcategory: "Glass Tanks",
    description: "حوض Boshuo YS-500 - الخيار الاقتصادي الذكي! جودة ممتازة بسعر معقول، مثالي للمبتدئين والخبراء. زجاج شفاف عالي الجودة مع زوايا محكمة الإغلاق. الحجم 50 سم مناسب تماماً للأحواض المجتمعية الصغيرة والمتوسطة. خفيف الوزن وسهل النقل والتركيب. يتحمل الظروف المختلفة ومناسب لجميع أنواع الأسماك. استثمار ذكي يوفر أداء موثوقاً دون كسر الميزانية! | Boshuo YS-500 Aquarium - the smart economic choice! Excellent quality at reasonable price, perfect for beginners and experts. High-quality clear glass with tightly sealed corners. 50cm size perfectly suited for small to medium community tanks. Lightweight, easy to transport and install. Withstands various conditions, suitable for all fish types. Smart investment providing reliable performance without breaking budget!",
    price: "125000",
    currency: "IQD",
    images: ["/products/boshuo-ys-500.jpg"],
    thumbnail: "/products/boshuo-ys-500.jpg",
    rating: "4.6",
    reviewCount: 124,
    stock: 22,
    lowStockThreshold: 5,
    isNew: false,
    isBestSeller: false,
    specifications: {
      dimensions: "50 x 28 x 32 cm (L x W x H)",
      volume: "45 liters",
      glassThickness: "5mm",
      weight: "9 kg (empty)",
      material: "Clear glass",
      sealant: "Aquarium-grade silicone",
      difficulty: "easy",
      suitableFor: "Community fish, Bettas, Small tropicals",
      maxFishLoad: "15-20 small fish",
      warranty: "6 months",
      ecoFriendly: true
    }
  },

  // ==================== FILTRATION SYSTEMS ====================
  {
    id: "sunsum-hw-603b-canister",
    slug: "sunsum-hw-603b-canister-filter",
    name: "SunSun HW-603B Canister Filter - فلتر خارجي",
    brand: "SunSun",
    category: "Filtration",
    subcategory: "Canister Filters",
    description: "فلتر SunSun HW-603B الخارجي - قوة ترشيح احترافية! نظام ترشيح متعدد المراحل (ميكانيكي، بيولوجي، كيميائي) يضمن مياه نقية كالكريستال. يعمل بهدوء شديد ولا يزعج الأسماك أو العائلة. سهل الصيانة مع وسائط قابلة للتبديل. معدل تدفق قابل للتعديل يناسب احتياجات حوضك. مثالي للأحواض حتى 100 لتر. استهلاك طاقة منخفض ومتانة عالية. الحل الأمثل للحفاظ على بيئة مائية صحية! | SunSun HW-603B Canister Filter - professional filtration power! Multi-stage filtration system (mechanical, biological, chemical) ensures crystal-clear water. Operates ultra-quietly, won't disturb fish or family. Easy maintenance with replaceable media. Adjustable flow rate suits your tank needs. Perfect for tanks up to 100 liters. Low energy consumption and high durability. Optimal solution for maintaining healthy aquatic environment!",
    price: "95000",
    currency: "IQD",
    images: ["/products/sunsun-hw-603b.jpg"],
    thumbnail: "/products/sunsun-hw-603b.jpg",
    rating: "4.7",
    reviewCount: 156,
    stock: 32,
    lowStockThreshold: 8,
    isNew: false,
    isBestSeller: true,
    specifications: {
      maxTankSize: "100 liters",
      flowRate: "400 L/hr",
      power: "6W",
      filterMedia: "Ceramic rings, sponge, activated carbon",
      stages: "3-stage filtration",
      dimensions: "18 x 18 x 28 cm",
      tubeSize: "12/16mm",
      noiseLevel: "Ultra-quiet operation",
      difficulty: "medium",
      maintenance: "Clean every 4-6 weeks",
      ecoFriendly: true,
      warranty: "1 year"
    }
  },
  {
    id: "hygger-hob-filter",
    slug: "hygger-hang-on-back-filter-hob",
    name: "HYGGER Hang-on-Back Filter - فلتر هايجر الخلفي",
    brand: "HYGGER",
    category: "Filtration",
    subcategory: "HOB Filters",
    description: "فلتر HYGGER المعلق - البساطة والفعالية! تصميم معلق خلفي لا يأخذ مساحة داخل الحوض. سهل التركيب - فقط علقه وشغله! ترشيح قوي بثلاث مراحل لمياه صافية ونظيفة. تدفق قابل للتعديل يناسب جميع أنواع الأسماك. صيانة فائقة السهولة - فقط اغسل الإسفنج شهرياً. مثالي للمبتدئين والأحواض الصغيرة إلى المتوسطة. سعر معقول وأداء ممتاز. استمتع بحوض نظيف دون عناء! | HYGGER Hang-on-Back Filter - simplicity and effectiveness! Back-hanging design takes no space inside tank. Easy installation - just hang and start! Powerful 3-stage filtration for clear, clean water. Adjustable flow suits all fish types. Ultra-easy maintenance - just rinse sponge monthly. Perfect for beginners and small to medium tanks. Reasonable price and excellent performance. Enjoy clean tank without hassle!",
    price: "45000",
    currency: "IQD",
    images: ["/products/hygger-hob.jpg"],
    thumbnail: "/products/hygger-hob.jpg",
    rating: "4.5",
    reviewCount: 201,
    stock: 48,
    lowStockThreshold: 12,
    isNew: false,
    isBestSeller: false,
    specifications: {
      maxTankSize: "75 liters",
      flowRate: "300 L/hr",
      power: "4W",
      filterMedia: "Bio-sponge, activated carbon",
      stages: "3-stage filtration",
      dimensions: "12 x 8 x 15 cm",
      installation: "Hang-on-back - no drilling",
      noiseLevel: "Quiet",
      difficulty: "easy",
      maintenance: "Very easy - rinse monthly",
      ecoFriendly: true,
      warranty: "6 months"
    }
  },

  // ==================== HEATING ====================
  {
    id: "wenfang-heater-200w",
    slug: "wenfang-submersible-heater-200w",
    name: "Wenfang Submersible Heater 200W - سخان 200 واط",
    brand: "Wenfang",
    category: "Equipment",
    subcategory: "Heaters",
    description: "سخان Wenfang 200W - الحرارة المثالية لأسماكك! تحكم دقيق في درجة الحرارة (±1°C) لضمان بيئة مستقرة. مصنوع من زجاج الكوارتز المقاوم للكسر والصدمات. ثرموستات أوتوماتيكي ذكي يحافظ على الحرارة المطلوبة بدقة. مؤشر LED يوضح حالة التشغيل. قابل للغمر بالكامل وآمن تماماً. واقي أمان يمنع الحرارة الزائدة. مثالي للأحواض 150-200 لتر. استثمر في صحة أسماكك مع تدفئة موثوقة! | Wenfang 200W Heater - perfect temperature for your fish! Precise temperature control (±1°C) ensuring stable environment. Made from shatterproof, shock-resistant quartz glass. Smart automatic thermostat maintains desired temperature accurately. LED indicator shows operating status. Fully submersible and completely safe. Safety guard prevents overheating. Ideal for 150-200 liter tanks. Invest in your fish health with reliable heating!",
    price: "38000",
    currency: "IQD",
    images: ["/products/wenfang-heater-200w.jpg"],
    thumbnail: "/products/wenfang-heater-200w.jpg",
    rating: "4.6",
    reviewCount: 143,
    stock: 54,
    lowStockThreshold: 15,
    isNew: false,
    isBestSeller: true,
    specifications: {
      power: "200W",
      suitableTankSize: "150-200 liters",
      temperatureRange: "20-34°C",
      accuracy: "±1°C",
      material: "Quartz glass",
      length: "28 cm",
      voltage: "220-240V",
      features: "LED indicator, Auto shut-off, Fully submersible",
      difficulty: "easy",
      installation: "Suction cups included",
      ecoFriendly: true,
      warranty: "1 year",
      safetyFeatures: "Overheat protection, Shatterproof"
    }
  },

  // ==================== LIGHTING ====================
  {
    id: "hygger-led-light-18w",
    slug: "hygger-full-spectrum-led-18w",
    name: "HYGGER Full Spectrum LED Light 18W - إضاءة LED 18 واط",
    brand: "HYGGER",
    category: "Equipment",
    subcategory: "Lighting",
    description: "إضاءة HYGGER LED بطيف كامل - اجعل حوضك يتألق! تقنية LED الحديثة بطيف كامل تحاكي ضوء الشمس الطبيعي. مثالية لنمو النباتات وإظهار ألوان الأسماك الزاهية. سطوع قابل للتعديل (0-100%) لخلق الإضاءة المثالية. مؤقت ذكي 24 ساعة لضبط دورة النهار/الليل تلقائياً. استهلاك طاقة منخفض جداً وعمر طويل (50,000 ساعة). تصميم نحيف وعصري يناسب جميع الأحواض. حول حوضك إلى تحفة فنية مضيئة! | HYGGER Full Spectrum LED Light - make your tank shine! Modern full spectrum LED technology mimics natural sunlight. Perfect for plant growth and displaying vibrant fish colors. Adjustable brightness (0-100%) creating ideal lighting. Smart 24-hour timer sets day/night cycle automatically. Very low energy consumption and long life (50,000 hours). Slim, modern design suits all tanks. Transform your aquarium into illuminated masterpiece!",
    price: "52000",
    currency: "IQD",
    images: ["/products/hygger-led-18w.jpg"],
    thumbnail: "/products/hygger-led-18w.jpg",
    rating: "4.8",
    reviewCount: 167,
    stock: 36,
    lowStockThreshold: 10,
    isNew: true,
    isBestSeller: true,
    specifications: {
      power: "18W",
      spectrum: "Full spectrum (6500K-8000K white + RGB)",
      suitableTankSize: "60-80 cm length",
      brightness: "Adjustable 0-100%",
      timer: "24-hour programmable",
      lifespan: "50,000 hours",
      dimensions: "58-68 cm extendable",
      features: "Dimmable, Timer, Multiple color modes",
      difficulty: "easy",
      plantGrowth: "Excellent for planted tanks",
      ecoFriendly: true,
      warranty: "2 years",
      energyEfficiency: "Very high - LED technology"
    }
  },

  // ==================== FISH FOOD ====================
  {
    id: "tetra-bits-complete",
    slug: "tetra-bits-complete-fish-food",
    name: "Tetra Bits Complete Fish Food - طعام تترا بيتس الكامل",
    brand: "Tetra",
    category: "Food",
    subcategory: "Pellets",
    description: "Tetra Bits - التغذية المتكاملة من العلامة التجارية الأولى عالمياً! تركيبة علمية متوازنة تلبي جميع احتياجات الأسماك الغذائية. حبيبات صغيرة سهلة البلع لجميع أنواع الأسماك الاستوائية. تعزز الألوان الطبيعية وتقوي المناعة. لا تعكر المياه وتحافظ على نقاوة الحوض. غنية بالبروتينات والفيتامينات والمعادن الأساسية. عبوة محكمة الإغلاق تحافظ على النضارة. استثمر في صحة أسماكك مع الأفضل! | Tetra Bits - complete nutrition from world's #1 brand! Scientific balanced formula meeting all fish dietary needs. Small, easy-to-swallow pellets for all tropical fish types. Enhances natural colors and strengthens immunity. Won't cloud water, maintains tank clarity. Rich in proteins, vitamins, and essential minerals. Airtight packaging preserves freshness. Invest in your fish health with the best!",
    price: "25000",
    currency: "IQD",
    images: ["/products/tetra-bits.jpg"],
    thumbnail: "/products/tetra-bits.jpg",
    rating: "4.9",
    reviewCount: 312,
    stock: 145,
    lowStockThreshold: 30,
    isNew: false,
    isBestSeller: true,
    specifications: {
      type: "Complete pellet food",
      size: "Small pellets",
      suitableFor: "All tropical fish",
      weight: "93g",
      features: "Color enhancing, Immune boosting, Clear water formula",
      ingredients: "Fish meal, wheat gluten, vitamins, minerals",
      protein: "46%",
      fat: "8%",
      fiber: "2%",
      feeding: "2-3 times daily, amount consumed in 3 minutes",
      shelfLife: "2 years",
      ecoFriendly: true
    }
  },

  // ==================== WATER TREATMENT ====================
  {
    id: "aqua-safe-conditioner",
    slug: "aqua-safe-water-conditioner",
    name: "AquaSafe Water Conditioner - مُهيئ المياه الآمن",
    brand: "AquaSafe",
    category: "Water Treatment",
    subcategory: "Conditioners",
    description: "AquaSafe - حماية فورية لأسماكك! يزيل الكلور والكلورامين والمعادن الثقيلة من ماء الصنبور فوراً. يضيف طبقة حماية طبيعية لجلد الأسماك. يحتوي على فيتامين B لتقليل الإجهاد. آمن 100% لجميع أنواع الأسماك والنباتات والبكتيريا النافعة. سهل الاستخدام - فقط أضف للماء قبل وضعه في الحوض. تركيز عالي - زجاجة واحدة تكفي لأشهر! ضروري لكل تغيير ماء وإعداد حوض جديد. | AquaSafe - instant protection for your fish! Instantly removes chlorine, chloramine, and heavy metals from tap water. Adds natural protective coating to fish skin. Contains vitamin B to reduce stress. 100% safe for all fish, plants, and beneficial bacteria. Easy to use - just add to water before putting in tank. High concentration - one bottle lasts months! Essential for every water change and new tank setup.",
    price: "32000",
    currency: "IQD",
    images: ["/products/aqua-safe.jpg"],
    thumbnail: "/products/aqua-safe.jpg",
    rating: "4.8",
    reviewCount: 267,
    stock: 88,
    lowStockThreshold: 20,
    isNew: false,
    isBestSeller: true,
    specifications: {
      volume: "500ml",
      treats: "Up to 2000 liters",
      activeIngredients: "Sodium thiosulfate, EDTA, Vitamin B",
      removes: "Chlorine, Chloramine, Heavy metals",
      dosage: "5ml per 20 liters",
      suitableFor: "All freshwater and saltwater aquariums",
      benefits: "Stress reduction, Slime coat protection",
      shelfLife: "3 years",
      difficulty: "easy",
      ecoFriendly: true,
      essential: "Must-have for all aquarium owners"
    }
  }
];

async function seed() {
  try {
    console.log("Starting comprehensive database seed...");
    console.log(`Total products to insert: ${seedProducts.length}`);

    for (const product of seedProducts) {
      console.log(`Inserting product: ${product.name}`);
      await db.insert(products).values(product).onConflictDoNothing();
    }

    console.log("✅ Database seeded successfully with professional product data!");
    console.log("📊 Features included:");
    console.log("  - SEO-optimized bilingual descriptions (Arabic & English)");
    console.log("  - Comprehensive specifications");
    console.log("  - Detailed care requirements");
    console.log("  - Professional product categorization");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
}

seed();
