import type { Product } from "./schema.js";

export const mockProducts: Product[] = [
  {
    id: "fluval-407",
    slug: "fluval-407",
    name: "فلتر كانستر Fluval 407",
    brand: "Fluval",
    category: "filtration",
    subcategory: "canister",
    description: "فلتر خارجي قوي لأحواض حتى 500 لتر مع أداء هادئ واستهلاك طاقة منخفض.",
    price: "285000",
    originalPrice: "310000",
    currency: "IQD",
    images: ["/assets/products/fluval-407.png"],
    thumbnail: "/assets/products/fluval-407.png",
    rating: "4.9",
    reviewCount: 48,
    stock: 12,
    lowStockThreshold: 4,
    isNew: false,
    isBestSeller: true,
    isProductOfWeek: true,
    specifications: {
      difficulty: "medium",
      ecoFriendly: true,
      videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
      explodedViewParts: [
        { id: "motor-head", name: "رأس المحرك", imageUrl: "/assets/parts/motor.png", description: "وحدة المحرك الصامتة القوية", x: 50, y: 15 },
        { id: "impeller-cover", name: "غطاء المروحة", imageUrl: "/assets/parts/impeller.png", description: "حماية للمروحة وتقليل الضوضاء", x: 65, y: 25 },
        { id: "canister-clips", name: "مشابك الإغلاق", imageUrl: "/assets/parts/clips.png", description: "مشابك قوية لضمان إغلاق محكم", x: 30, y: 35 },
        { id: "media-baskets", name: "سلات الفلتر", imageUrl: "/assets/parts/baskets.png", description: "سلات متعددة لطبقات الفلترة", x: 50, y: 55 },
        { id: "canister-body", name: "جسم الفلتر", imageUrl: "/assets/parts/body.png", description: "سعة كبيرة لتخزين الوسائط", x: 50, y: 80 },
      ],
    },
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date("2024-11-15"),
    categoryId: null,
    deletedAt: null,
  },
  {
    id: "aquaclear-70",
    slug: "aquaclear-70",
    name: "فلتر شلال AquaClear 70",
    brand: "AquaClear",
    category: "filtration",
    subcategory: "hob",
    description: "فلتر ظهر الحوض الشهير بكفاءة عالية وتدفق قابل للتعديل لأحواض 150-265 لتر.",
    price: "125000",
    originalPrice: "145000",
    currency: "IQD",
    images: ["/assets/products/aquaclear-70.png"],
    thumbnail: "/assets/products/aquaclear-70.png",
    rating: "4.6",
    reviewCount: 32,
    stock: 20,
    lowStockThreshold: 5,
    isNew: false,
    isBestSeller: true,
    isProductOfWeek: false,
    specifications: {
      difficulty: "easy",
      ecoFriendly: true,
    },
    createdAt: new Date("2024-08-12"),
    updatedAt: new Date("2024-11-20"),
    categoryId: null,
    deletedAt: null,
  },
  {
    id: "seachem-prime",
    slug: "seachem-prime-500ml",
    name: "مُكيف مياه Seachem Prime 500ml",
    brand: "Seachem",
    category: "water-care",
    subcategory: "conditioner",
    description: "إزالة الكلور والكلورامين وتحييد الأمونيا لحماية الأسماك خلال تغييرات المياه.",
    price: "55000",
    originalPrice: null,
    currency: "IQD",
    images: ["/assets/products/seachem-prime.png"],
    thumbnail: "/assets/products/seachem-prime.png",
    rating: "4.8",
    reviewCount: 67,
    stock: 40,
    lowStockThreshold: 6,
    isNew: false,
    isBestSeller: true,
    isProductOfWeek: false,
    specifications: {
      difficulty: "easy",
      ecoFriendly: true,
    },
    createdAt: new Date("2024-07-02"),
    updatedAt: new Date("2024-11-10"),
    categoryId: null,
    deletedAt: null,
  },
  {
    id: "eheim-jager-200w",
    slug: "eheim-jager-200w",
    name: "سخان EHEIM Jager 200W",
    brand: "EHEIM",
    category: "heating",
    subcategory: "heater",
    description: "سخان زجاجي دقيق مع حماية من الجفاف وتصحيح حرارة عالي الدقة.",
    price: "95000",
    originalPrice: null,
    currency: "IQD",
    images: ["/assets/products/eheim-jager-200w.png"],
    thumbnail: "/assets/products/eheim-jager-200w.png",
    rating: "4.7",
    reviewCount: 28,
    stock: 18,
    lowStockThreshold: 5,
    isNew: false,
    isBestSeller: true,
    isProductOfWeek: false,
    specifications: {
      difficulty: "easy",
      ecoFriendly: false,
    },
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-11-05"),
    categoryId: null,
    deletedAt: null,
  },
];
